# Generated by Django 5.0 on 2026-03-25 12:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('logo_text', models.CharField(blank=True, default='', max_length=10)),
                ('scraped_source', models.CharField(default='weworkremotely', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('job_type', models.CharField(blank=True, default='', max_length=255)),
                ('salary', models.CharField(blank=True, default='', max_length=255)),
                ('salary_range', models.CharField(blank=True, default='', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('posted_text', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('scraped_term', models.CharField(blank=True, default='', max_length=255)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='App.company')),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='App_job_title_84dfc4_idx'), models.Index(fields=['location'], name='App_job_locatio_25ae1b_idx'), models.Index(fields=['scraped_term'], name='App_job_scraped_da1f68_idx'), models.Index(fields=['scraped_at'], name='App_job_scraped_4c1791_idx')],
            },
        ),
    ]
