# Generated by Django 5.0 on 2026-03-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='App_job_title_84dfc4_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='App_job_locatio_25ae1b_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='App_job_scraped_da1f68_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='App_job_scraped_4c1791_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='apply_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_text',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scraped_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='scraped_term',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='job',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='remote',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
